# Site settings
title: Adhy Suryadi Blog
subtitle: "Coretan kisah sebuah kehidupan"
header-img: img/home-bg.jpg
image: img/home-bg.jpg
copyright_name: Adhy Suryadi Blog
description: "Coretan kisah sebuah kehidupan, berbagi dengan sesama tentang pengalaman hidup."
url: "http://adhysuryadi.xyz"
author: Adhy Suryadi
twitter_username: KompiAjaib
github_username:  KompiAjaib
facebook_username:  adhy.suryadii
email_username:  kompiajaib@gmail.com

# Build settings
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: false
permalink: /:title/
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed, jekyll-sitemap]

# html minify
compress_html:
  clippings: all
  comments: ["<!--","-->"]
  endings: []
  profile: false
  ignore:
  comments: ["<!--</body>-->"]
