# Site settings
title: Adhy Suryadi Blog
header-img: img/home-bg.jpg
email: kompiajaib@gmail.com
copyright_name: Adhy Suryadi Blog
description: "Coretan kisah sebuah kehidupan."
url: "http://kompiajaib.github.io"
twitter_username: KompiAjaib
github_username:  KompiAjaib
facebook_username:  adhy.suryadii
email_username:  kompiajaib@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

# Settings for comments helper
# Set 'provider' to the comment provider you want to use.
# Set 'provider' to false to turn commenting off globally.
#
comments :
  provider : disqus
  disqus :
    short_name : adhysuryadiblog
